<?php
global $systemProperties;

$systemProperties = array();
$systemProperties['system'] = array();

$systemProperties['system']['isWhiteLabel'] = true;
$systemProperties['system']['partnerFooterUrl'] = '';
$systemProperties['system']['purchased'] = array();

$systemProperties['system']['purchased']['yola_footer_removal']['enabled'] = true;
$systemProperties['system']['purchased']['css_overrides']['enabled'] = false;
$systemProperties['system']['purchased']['custom_tracking']['enabled'] = false;

// Ecommerce features
$systemProperties['system']['purchased']['ecommerce']['enabled'] = false;
$systemProperties['system']['purchased']['ecommerce']['storeId'] = '';

$systemProperties['system']['locale'] = 'pt-br';
$systemProperties['system']['partnerId'] = 'WL_UOLHOST';
$systemProperties['system']['facebookPageId'] = '';

//Define user properties
$systemProperties['system']['user'] = array();
$userProperties =& $systemProperties['system']['user'];
$userProperties['id'] = 'dc332f5e41f94759983540728d3e1743';
$userProperties['signupDate'] = '2017-03-30 20:05:50';

//Define site properties
$systemProperties['system']['site'] = array();
$siteProperties =& $systemProperties['system']['site'];

$siteProperties['id'] = 'c8ad2363d34541c3b52415ac7eba90cc';
$siteProperties['facebookPageId'] = '';
$siteProperties['name'] = 'santstec';
$siteProperties['lastModified'] = '1490906775';

$systemProperties['system']['template'] = array();
$systemProperties['system']['template']['name'] = 'Skyline_v2';
$systemProperties['system']['template']['mobile']['name'] = 'Mobile';

$systemProperties['system']['template']['author'] = array();
$systemProperties['system']['template']['author']['name'] = 'Yola';
$systemProperties['system']['template']['author']['link'] = 'http://www.yola.com';

//Define authentication details
$systemProperties['system']['site']['auth'] = array();
$authDetails =& $systemProperties['system']['site']['auth'];

$authDetails['user'] = '';
$authDetails['pass'] = '';

            $systemProperties['properties']['content']['background-color'] = 'rgba(228,227,224,1.00)';
                $systemProperties['properties']['h2']['text-decoration'] = 'none';
                $systemProperties['properties']['nav']['text-transform'] = 'uppercase';
                $systemProperties['properties']['a:hover']['text-decoration'] = 'underline';
                $systemProperties['properties']['h4']['font-size'] = '1rem';
                $systemProperties['properties']['h4']['text-decoration'] = 'none';
                $systemProperties['properties']['phone']['main'] = '';
                $systemProperties['properties']['button']['medium']['font-size'] = '1rem';
                $systemProperties['properties']['body']['background-position'] = 'top left';
                $systemProperties['properties']['nav:hover']['color'] = '#db5021';
                $systemProperties['properties']['button']['medium']['padding-left'] = '2.5rem';
                $systemProperties['properties']['button']['small']['line-height'] = '';
                $systemProperties['properties']['button']['medium']['font-weight'] = '';
                $systemProperties['properties']['button']['large']['letter-spacing'] = '';
                $systemProperties['properties']['header']['background-color'] = '';
                $systemProperties['properties']['h1']['font-size'] = '2.2rem';
                $systemProperties['properties']['blockquote']['font-family'] = '';
                $systemProperties['properties']['footer']['display'] = 'none';
                $systemProperties['properties']['site']['tagline']['color'] = '#ffffff';
                $systemProperties['properties']['header']['alignment'] = 'left';
                $systemProperties['properties']['banner']['foreground-color'] = '';
                $systemProperties['properties']['button']['small']['color'] = '#ffffff';
                $systemProperties['properties']['h1']['text-decoration'] = 'none';
                $systemProperties['properties']['footer']['font-size'] = '1rem';
                $systemProperties['properties']['footer']['padding-bottom'] = '2.5rem';
                $systemProperties['properties']['banner']['padding-right'] = '9.4rem';
                $systemProperties['properties']['h4']['line-height'] = '1.5em';
                $systemProperties['properties']['nav']['background-color'] = '';
                $systemProperties['properties']['nav:selected']['color'] = '#db5021';
                $systemProperties['properties']['style_designer']['enabled'] = 'true';
                $systemProperties['properties']['css']['fonts'] = '@import url(\'//fonts.googleapis.com/css?family=Lato|Open+Sans\');.sys_navigation, #sys_heading, div#heading_wrapper a, div#menu ul, H1, H2, H3, H4, H5, H6, #content h1, #content h2, #content h3, #content h4, #content h5, #content h6, #content_wrapper #content_inner_wrapper h1, #content_wrapper #content_inner_wrapper h2, #content_wrapper #content_inner_wrapper h3, #content_wrapper #content_inner_wrapper h4, #headline_wrapper a,div#menu ul li a, a#sys_heading, .decay, .decay-small, .ys_menu_2  {font-family: Lato;}.content, #content, .HTML_Default, .Text_Default, .sys_txt  {font-family: Open Sans;}';
                $systemProperties['properties']['address']['postal_code'] = '';
                $systemProperties['properties']['header']['padding-right'] = '9.4rem';
                $systemProperties['properties']['site']['tagline']['background-color'] = '';
                $systemProperties['properties']['header']['content']['max-width'] = '';
                $systemProperties['properties']['h2']['line-height'] = '1.5em';
                $systemProperties['properties']['heading']['style'] = '';
                $systemProperties['properties']['body']['background-size'] = 'auto';
                $systemProperties['properties']['h3']['letter-spacing'] = '1px';
                $systemProperties['properties']['a:visited']['color'] = '#db5021';
                $systemProperties['properties']['h3']['font-family'] = '\'Lato\'';
                $systemProperties['properties']['blockquote']['background-color'] = '';
                $systemProperties['properties']['h2']['color'] = '#a2a08a';
                $systemProperties['properties']['h5']['color'] = '#7a7a7a';
                $systemProperties['properties']['h2']['font-size'] = '1.9rem';
                $systemProperties['properties']['footer']['padding-left'] = '3.8rem';
                $systemProperties['properties']['mobile']['map']['enabled'] = 'true';
                $systemProperties['properties']['mobile']['header']['font-color'] = '#ffffff';
                $systemProperties['properties']['body']['background-image'] = '';
                $systemProperties['properties']['site']['tagline']['padding-top'] = '';
                $systemProperties['properties']['banner']['padding-left'] = '9.4rem';
                $systemProperties['properties']['nav']['color'] = '#ffffff';
                $systemProperties['properties']['button']['medium']['background-color'] = 'rgba(219,80,33,1.00)';
                $systemProperties['properties']['banner']['src'] = 'resources/site_em_construcao.png';
                $systemProperties['properties']['h1']['text-transform'] = 'uppercase';
                $systemProperties['properties']['nav']['font-family'] = '\'Montserrat\'';
                $systemProperties['properties']['p']['line-height'] = '1.5em';
                $systemProperties['properties']['h3']['line-height'] = '1.5em';
                $systemProperties['properties']['banner']['display'] = 'block';
                $systemProperties['properties']['google']['businessCategories'] = '';
                $systemProperties['properties']['address']['state'] = '';
                $systemProperties['properties']['site']['google_fonts'] = '{"fonts": ["Montserrat:regular", "Lato:regular", "Open Sans:regular"]}';
                $systemProperties['properties']['header']['max-width'] = '1280px';
                $systemProperties['properties']['nav']['spacing'] = '40px';
                $systemProperties['properties']['h6']['text-decoration'] = '';
                $systemProperties['properties']['description'] = '';
                $systemProperties['properties']['button']['large']['background-color'] = 'rgba(219,80,33,1.00)';
                $systemProperties['properties']['tracking']['footer'] = '';
                $systemProperties['properties']['blockquote']['letter-spacing'] = '';
                $systemProperties['properties']['banner']['padding-bottom'] = '16.9rem';
                $systemProperties['properties']['h5']['font-size'] = '0.8rem';
                $systemProperties['properties']['footer']['padding-right'] = '3.8rem';
                $systemProperties['properties']['button']['small']['text-transform'] = '';
                $systemProperties['properties']['button']['medium']['letter-spacing'] = '';
                $systemProperties['properties']['h4']['text-transform'] = 'uppercase';
                $systemProperties['properties']['p']['color'] = '#797979';
                $systemProperties['properties']['h1']['font-weight'] = '';
                $systemProperties['properties']['header']['padding-bottom'] = '2.5rem';
                $systemProperties['properties']['button']['small']['shape'] = 'square';
                $systemProperties['properties']['nav']['font-weight'] = '';
                $systemProperties['properties']['address']['country'] = '';
                $systemProperties['properties']['h6']['line-height'] = '1.5em';
                $systemProperties['properties']['h2']['letter-spacing'] = '1px';
                $systemProperties['properties']['button']['large']['line-height'] = '';
                $systemProperties['properties']['h1']['text-align'] = 'center';
                $systemProperties['properties']['body']['padding-top'] = '';
                $systemProperties['properties']['banner']['background-size'] = 'cover';
                $systemProperties['properties']['banner']['background-color'] = '';
                $systemProperties['properties']['nav']['text-align'] = 'center';
                $systemProperties['properties']['h1']['font-family'] = '\'Lato\'';
                $systemProperties['properties']['h6']['font-family'] = '\'Lato\'';
                $systemProperties['properties']['site']['tagline']['text-decoration'] = 'none';
                $systemProperties['properties']['business_hours'] = 'null';
                $systemProperties['properties']['footer']['font-family'] = '\'Lato\'';
                $systemProperties['properties']['footer']['letter-spacing'] = '';
                $systemProperties['properties']['site']['tagline']['text-transform'] = 'uppercase';
                $systemProperties['properties']['h2']['font-family'] = '\'Montserrat\'';
                $systemProperties['properties']['body']['background-color'] = '#2f2c2a';
                $systemProperties['properties']['button']['small']['font-family'] = '\'Montserrat\'';
                $systemProperties['properties']['mobile']['call']['enabled'] = 'true';
                $systemProperties['properties']['h2']['text-transform'] = 'none';
                $systemProperties['properties']['nav']['line-height'] = '1.5em';
                $systemProperties['properties']['p']['letter-spacing'] = '';
                $systemProperties['properties']['h1']['letter-spacing'] = '1px';
                $systemProperties['properties']['button']['large']['text-transform'] = '';
                $systemProperties['properties']['p']['text-transform'] = 'none';
                $systemProperties['properties']['content']['padding-right'] = '3rem';
                $systemProperties['properties']['footer']['line-height'] = '1.5em';
                $systemProperties['properties']['button']['small']['padding-top'] = '0.6rem';
                $systemProperties['properties']['site']['logo']['width'] = '';
                $systemProperties['properties']['nav']['sub-menu-type'] = '';
                $systemProperties['properties']['button']['large']['font-family'] = '\'Montserrat\'';
                $systemProperties['properties']['button']['small']['padding-left'] = '1.5rem';
                $systemProperties['properties']['meta']['favicon'] = '';
                $systemProperties['properties']['h1']['line-height'] = '1.5em';
                $systemProperties['properties']['button']['medium']['font-family'] = '\'Montserrat\'';
                $systemProperties['properties']['button']['medium']['color'] = '#ffffff';
                $systemProperties['properties']['banner']['padding-top'] = '16.9rem';
                $systemProperties['properties']['address']['line1'] = '';
                $systemProperties['properties']['address']['line2'] = '';
                $systemProperties['properties']['button']['large']['padding-top'] = '1.3rem';
                $systemProperties['properties']['button']['large']['font-weight'] = '\'regular\'';
                $systemProperties['properties']['blockquote']['color'] = '';
                $systemProperties['properties']['button']['small']['background-color'] = 'rgba(219,80,33,1.00)';
                $systemProperties['properties']['css']['overrides'] = '.sys_yola_form .submit {
  background-color:#db5021; 
  color:#ffffff;
  padding: 10px 40px;
  border: solid 2px #db5021;
}';
                $systemProperties['properties']['p']['font-family'] = '\'Open Sans\'';
                $systemProperties['properties']['content']['content']['max-width'] = '1060px';
                $systemProperties['properties']['mobile']['enabled'] = '';
                $systemProperties['properties']['button']['medium']['shape'] = 'square';
                $systemProperties['properties']['footer']['text-transform'] = 'none';
                $systemProperties['properties']['tracking']['header'] = '';
                $systemProperties['properties']['h6']['color'] = '#7a7a7a';
                $systemProperties['properties']['footer']['text'] = '';
                $systemProperties['properties']['nav']['letter-spacing'] = '1px';
                $systemProperties['properties']['tracking']['gaid'] = '';
                $systemProperties['properties']['footer']['background-color'] = '';
                $systemProperties['properties']['footer']['padding-top'] = '2.5rem';
                $systemProperties['properties']['button']['medium']['style'] = 'solid';
                $systemProperties['properties']['blockquote']['font-weight'] = '';
                $systemProperties['properties']['banner']['background-repeat'] = 'no-repeat';
                $systemProperties['properties']['blockquote']['line-height'] = '';
                $systemProperties['properties']['p']['font-size'] = '1rem';
                $systemProperties['properties']['site']['tagline']['font-weight'] = '';
                $systemProperties['properties']['site']['tagline']['text'] = '';
                $systemProperties['properties']['button']['small']['font-size'] = '0.8rem';
                $systemProperties['properties']['a:link']['color'] = '#db5021';
                $systemProperties['properties']['button']['medium']['padding-top'] = '0.8rem';
                $systemProperties['properties']['footer']['color'] = '#7a7a7a';
                $systemProperties['properties']['sitetemplate'] = '1e9dbfee-24d9-471e-842b-8be807c8c489';
                $systemProperties['properties']['button']['large']['color'] = '#ffffff';
                $systemProperties['properties']['a:link']['text-decoration'] = 'none';
                $systemProperties['properties']['button']['medium']['line-height'] = '';
                $systemProperties['properties']['address']['city'] = '';
                $systemProperties['properties']['h5']['letter-spacing'] = '1px';
                $systemProperties['properties']['content']['max-width'] = '1280px';
                $systemProperties['properties']['site']['tagline']['padding-right'] = '';
                $systemProperties['properties']['h1']['color'] = '#7a7a7a';
                $systemProperties['properties']['p']['font-weight'] = '\'regular\'';
                $systemProperties['properties']['h4']['font-weight'] = '';
                $systemProperties['properties']['page']['vertical-align'] = 'top';
                $systemProperties['properties']['body']['background-repeat'] = 'repeat';
                $systemProperties['properties']['h6']['font-size'] = '0.7rem';
                $systemProperties['properties']['h4']['font-family'] = '\'Lato\'';
                $systemProperties['properties']['footer']['font-weight'] = '';
                $systemProperties['properties']['h5']['font-family'] = '\'Lato\'';
                $systemProperties['properties']['button']['large']['shape'] = 'square';
                $systemProperties['properties']['site']['tagline']['letter-spacing'] = '2px';
                $systemProperties['properties']['h5']['line-height'] = '1.5em';
                $systemProperties['properties']['body']['padding-bottom'] = '2.5rem';
                $systemProperties['properties']['body']['foreground-color'] = '';
                $systemProperties['properties']['nav']['font-size'] = '0.9rem';
                $systemProperties['properties']['button']['medium']['text-transform'] = '';
                $systemProperties['properties']['footer']['socialbuttons']['display'] = 'none';
                $systemProperties['properties']['site']['tagline']['padding-left'] = '';
                $systemProperties['properties']['content']['padding-left'] = '3rem';
                $systemProperties['properties']['button']['small']['font-weight'] = '\'\'regular\'\'';
                $systemProperties['properties']['a:hover']['color'] = '#797979';
                $systemProperties['properties']['body']['padding-left'] = '0rem';
                $systemProperties['properties']['header']['padding-top'] = '2.5rem';
                $systemProperties['properties']['h6']['font-weight'] = '';
                $systemProperties['properties']['button']['large']['padding-left'] = '3.1rem';
                $systemProperties['properties']['site']['tagline']['text-align'] = 'left';
                $systemProperties['properties']['h4']['letter-spacing'] = '1px';
                $systemProperties['properties']['site']['tagline']['line-height'] = '1.5em';
                $systemProperties['properties']['h3']['text-decoration'] = 'none';
                $systemProperties['properties']['mobile']['header']['background-color'] = '#006699';
                $systemProperties['properties']['h5']['text-decoration'] = 'none';
                $systemProperties['properties']['meta']['googleWebmaster'] = '';
                $systemProperties['properties']['h4']['color'] = '#ffffff';
                $systemProperties['properties']['h3']['font-size'] = '1.1rem';
                $systemProperties['properties']['site']['tagline']['font-size'] = '3.1rem';
                $systemProperties['properties']['blockquote']['font-size'] = '';
                $systemProperties['properties']['nav']['text-decoration'] = 'none';
                $systemProperties['properties']['nav']['padding'] = '1.1rem';
                $systemProperties['properties']['h6']['letter-spacing'] = '1px';
                $systemProperties['properties']['blockquote']['text-transform'] = '';
                $systemProperties['properties']['site']['logo']['src'] = '';
                $systemProperties['properties']['site']['tagline']['padding-bottom'] = '';
                $systemProperties['properties']['h3']['text-transform'] = 'uppercase';
                $systemProperties['properties']['button']['small']['letter-spacing'] = '';
                $systemProperties['properties']['body']['background-attachment'] = 'fixed';
                $systemProperties['properties']['css']['overrides-enabled'] = 'true';
                $systemProperties['properties']['banner']['background-position'] = 'center center';
                $systemProperties['properties']['header']['padding-left'] = '9.4rem';
                $systemProperties['properties']['banner']['content']['max-width'] = '';
                $systemProperties['properties']['h5']['font-weight'] = '';
                $systemProperties['properties']['content']['padding-top'] = '3rem';
                $systemProperties['properties']['h3']['font-weight'] = '';
                $systemProperties['properties']['content']['padding-bottom'] = '3rem';
                $systemProperties['properties']['h6']['text-transform'] = 'uppercase';
                $systemProperties['properties']['h3']['color'] = '#7a7a7a';
                $systemProperties['properties']['banner']['max-width'] = '1280px';
                $systemProperties['properties']['mobile']['banner']['enabled'] = 'true';
                $systemProperties['properties']['h5']['text-transform'] = 'uppercase';
                $systemProperties['properties']['google']['placesOptIn'] = '';
                $systemProperties['properties']['text_widget_mode'] = '';
                $systemProperties['properties']['button']['large']['font-size'] = '1.3rem';
                $systemProperties['properties']['h2']['font-weight'] = '';
                $systemProperties['properties']['button']['large']['style'] = 'solid';
                $systemProperties['properties']['site']['tagline']['font-family'] = '\'Montserrat\'';
                $systemProperties['properties']['body']['padding-right'] = '0rem';
                $systemProperties['properties']['css']['style-enabled'] = 'true';
                $systemProperties['properties']['site_location_feature'] = '';
                $systemProperties['properties']['button']['small']['style'] = 'solid';
                $systemProperties['properties']['blockquote']['font-style'] = 'italic';
    
//Define navigation structure
$systemProperties['system']['site']['navigation'] = array();
$navigation =& $systemProperties['system']['site']['navigation'];

	$currNavEntry =& $navigation[];
	$currNavEntry['name'] = 'Página inicial';
	$currNavEntry['title'] = 'Página inicial';
	$currNavEntry['href'] = 'index.php';

                
	$currNavEntry =& $navigation[];
	$currNavEntry['name'] = 'Contato';
	$currNavEntry['title'] = 'Contato';
	$currNavEntry['href'] = 'contact.php';

                
?>